name: Python package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment for the specified Python version (3.7)
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Upgrade pip and install dependencies (JAX)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jax

    # Step 4: Install the uwmanifeld package (assuming it has a setup.py or equivalent)
    - name: Install uwmanifeld package
      run: |
        if [ -f setup.py ]; then python setup.py install; fi

    # Step 5: Optional - You can add any commands here to test or validate your package
    - name: Check version (placeholder test)
      run: python -c "import uwmanifeld; print(uwmanifeld.__version__)"
